spring:
  debug: true
  config:
      import: classpath:env.properties
  main:
    allow-bean-definition-overriding: true
  application:
    name: testFirst
  redis:
    host: localhost
    port: 6379

weatherapi:
  base-url: ${WEATHER_API_BASE_URL}
  key: ${WEATHER_API_KEY}
