


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: testFirst
  redis:
    host: localhost
    port: 6379

weatherapi:
  base-url: "https://api.weatherapi.com/v1"
  key: "0e3f6c2db0364a15a2941201250712"





